#include "idt.h"

#include "console.h"
#include "pic.h"
#include "io.h"
#include "keyboard.h"
#include "clock.h"
#include "syscalls.h"

#include "libk/stdio.h"
#include <scheduler.h>
#include <utils.h>

#ifdef __x86_64__
typedef unsigned long long int uword_t;
#else
typedef unsigned int uword_t;
#endif

struct interrupt_frame;

struct IDTEntry {
    uint16_t    baseLo;
    uint16_t    selector;
    uint8_t     reserved; // = 0
    uint8_t     flags;
    uint16_t    baseHi;
} __attribute__((packed));

struct IDTPtr {
    uint16_t limit;
    uint32_t base;
} __attribute__((packed));

struct IDTEntry    idt[256];
struct IDTPtr      idtp;

#define INTERRUPT __attribute__((interrupt))
#define ISR(name)  static INTERRUPT void name(struct interrupt_frame *frame)
#define ISRE(name) static INTERRUPT void name(struct interrupt_frame *frame, uword_t errorCode)
#define HALT __asm__("cli\n\thlt");
#define ISR_MSG(name, message) ISR(name){ UNUSED(frame); printf(#message); HALT;}

#define ISR_DRIVER(name) \
    extern void _##name(void);\
    __asm__(".global _"#name"\n\t"\
            "_"#name":\n\t"\
            "cld\n\t"\
            "pusha\n\t"\
            "call "#name"\n\t"\
            "popa\n\t"\
            "iret");

static void idt_load(struct IDTPtr *idt_ptr)
{
    __asm__ __volatile__(
        "lidt (%0)\n"
        "sti" : : "r"(idt_ptr)
    );
}

ISR(isr_default)
{
    HALT;
}

ISR_MSG(isr0,  "[!] Exception 0: Division by zero\n");
ISR_MSG(isr4,  "[!] Exception 4: Overflow\n");
ISR_MSG(isr5,  "[!] Exception 5: Bound range exceded\n");


// TODO: Impelment invalid opcode handler to show which opcode cause the fault and at which address
// ISR_MSG(isr6,  "[!] Exception 6: Invalid opcode\n");

ISRE(isr6)
{
    puts("[!] Exception 6: Invalid opcode");
    printf("\tAddress: %x\n", errorCode);
    HALT
}

ISR_MSG(isr7,  "[!] Exception 7: Device not available\n");
ISR_MSG(isr8,  "[!] Exception 8: Double fault\n");

ISRE(isr13) {
    __asm__ __volatile__ ("cli");
    console_clear();
    puts("[!] Exception 13: General protection fault");
    dump_regs();
    uint32_t eip;
    __asm__ __volatile__ ("movl -4(%%esp), %0" : "=r"(eip));
    printf("eip = %x\n", eip);
    printf("error code: %x\n", errorCode);
    dump_pagetable();
    HALT;
}

#define  PAGE_FAULT_PRESENT     0x01
#define  PAGE_FAULT_WRITE       0x02
#define  PAGE_FAULT_USER        0x04
#define  PAGE_FAULT_RESERVED    0x08
#define  PAGE_FAULT_FETCH       0x10
#define  PAGE_FAULT_PROTECTION  0x20
#define  PAGE_FAULT_SHADOW      0x40
#define  PAGE_FAULT_SGX         0x80
//  Page faults handler
ISRE(isr14)
{
    printf("[!] Exception 14 - Page fault - ");
    if (errorCode & PAGE_FAULT_PRESENT) {
        printf("Page-protection violation ");
    } else {
        printf("Non-present page ");
    }
    if (errorCode & PAGE_FAULT_WRITE) {
        printf("on page write ");
    } else {
        printf("on page read ");
    }
    if (errorCode & PAGE_FAULT_USER) {
        printf("while CPL = 3 ");
    }
    if (errorCode & PAGE_FAULT_RESERVED) {
        printf("caused by reading 1 in reserved field ");
    }
    if (errorCode & PAGE_FAULT_FETCH) {
        printf("Caused by instructon fetch");
    }

    // CR2 is set to the virtual address that caused the page fault
    register uint32_t faultAddr;
    __asm__ __volatile__("movl %%cr2, %0" : "=r"(faultAddr));
    printf("\nAddress: %x\n", faultAddr);
    HALT;
}

ISR_DRIVER(isr_128);

// Interrupt servicing system calls
void isr_128(syscall_frame_t frame)
{
    void (*apicall)(struct syscall_frame*) = syscalls[frame.eax];
    apicall(&frame);
}

extern clock_t clock;

// Interrupt servicing timer
ISR_DRIVER(isr_timer);
void isr_timer(syscall_frame_t frame)
{
    // Interrupt generated by PIT, so we increments ticks counter
    clock.ticks += 1;
    if (clock.ticks % 100 == 0) {
        clock.seconds += 1;
        // switch_process((uint32_t*)(&frame.eax)+1, &frame);
    }

    // Acknowledge interrupt handling to PIC so we can resume interrupts
    pic_ack(PIC1);
}

// Handler for keyboard interrupts
ISR(isr_keyboard)
{
    uint8_t scancode = inb(0x60);
    if (scancode & 0x80) {
        /* You can use this one to see if the user released the
        *  shift, alt, or control keys... */
    } else {
        char c = keyboardUS[scancode];
        console_put_char(c);
    }
    pic_ack(PIC1);
}

static void idt_install()
{
    idtp.limit = sizeof(struct IDTEntry) * 256 - 1;
    idtp.base = (uint32_t)&idt;
    idt_load(&idtp);
}

#define IDT_ENTRY_PRESENT 0x80

static void idt_set_gate(uint8_t num, uint32_t base, uint16_t sel,
                         uint8_t gate_type, uint8_t dpl)
{
    idt[num].flags    = IDT_ENTRY_PRESENT | ((dpl & 0x3) << 5) | (gate_type & 0xf);
    idt[num].selector = sel;
    idt[num].baseLo   = (base & 0x0000ffff);
    idt[num].baseHi   = (base & 0xffff0000) >> 16;
}

static void* idt_get_gate(uint8_t num)
{
    uint32_t ret;
    ret = idt[num].baseLo | (idt[num].baseHi << 16);
    return (void*)ret;
}

#define  KERNEL_CODE_GDT_SELECTOR  0x8
#define  GATE_TYPE_TASK            0x5
#define  GATE_TYPE_16_INTERRUPT    0x6
#define  GATE_TYPE_16_TRAP         0x7
#define  GATE_TYPE_32_INTERRUPT    0xE
#define  GATE_TYPE_32_TRAP         0xF

ISR(isr_syscall) {
    puts("[#] Kernel syscall");
    HALT;
}

void idt_init()
{
    // Initialize all gates with generic handler
    for (int i = 0; i < 256; ++i) {
        idt_set_gate(i, (uint32_t)isr_default,  KERNEL_CODE_GDT_SELECTOR, GATE_TYPE_32_INTERRUPT, 0);
    }

    // Specific handlers
    idt_set_gate(0,    (uint32_t)isr0,          KERNEL_CODE_GDT_SELECTOR, GATE_TYPE_32_INTERRUPT, 0);
    idt_set_gate(4,    (uint32_t)isr4,          KERNEL_CODE_GDT_SELECTOR, GATE_TYPE_32_INTERRUPT, 0);
    idt_set_gate(5,    (uint32_t)isr5,          KERNEL_CODE_GDT_SELECTOR, GATE_TYPE_32_INTERRUPT, 0);
    idt_set_gate(6,    (uint32_t)isr6,          KERNEL_CODE_GDT_SELECTOR, GATE_TYPE_32_INTERRUPT, 0);
    idt_set_gate(7,    (uint32_t)isr7,          KERNEL_CODE_GDT_SELECTOR, GATE_TYPE_32_INTERRUPT, 0);
    idt_set_gate(8,    (uint32_t)isr8,          KERNEL_CODE_GDT_SELECTOR, GATE_TYPE_32_INTERRUPT, 0);
    idt_set_gate(13,   (uint32_t)isr13,         KERNEL_CODE_GDT_SELECTOR, GATE_TYPE_32_INTERRUPT, 0);
    idt_set_gate(14,   (uint32_t)isr14,         KERNEL_CODE_GDT_SELECTOR, GATE_TYPE_32_INTERRUPT, 0);
    idt_set_gate(0x20, (uint32_t)_isr_timer,    KERNEL_CODE_GDT_SELECTOR, GATE_TYPE_32_INTERRUPT, 0);
    idt_set_gate(0x21, (uint32_t)isr_keyboard,  KERNEL_CODE_GDT_SELECTOR, GATE_TYPE_32_INTERRUPT, 0);
    idt_set_gate(0x80, (uint32_t)isr_syscall,   KERNEL_CODE_GDT_SELECTOR, GATE_TYPE_32_INTERRUPT, 3);

    idt_install();
}
